spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-tron-db
    username: root
    password: 123456
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    username: teamperligo@gmail.com
    password: sozcpjyaalcbzosf
    properties:
      smtp:
        starttls:
          enable: true
        auth: true
    port: 587